import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Custom components
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modal/LoginModal";
import SignUpModal from "./components/modal/SignUpModal";
import AddPropertiesModal from "./components/modal/AddPropertiesModal";
import DeleteModal from "./components/modal/DeleteModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Django Bnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = <p>This is a contnent</p>;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-32">{children}</div>
        <LoginModal />
        <SignUpModal />
        <DeleteModal />
        <AddPropertiesModal />
      </body>
    </html>
  );
}
